name: zippoppow
favicon: null
layout_spectrum: 0.17034793109633029
typography_spectrum: 0.5989071426447481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6048843404278159
  lightness: 0.023327881935983896
  saturation: 0.21151286852546036
  rhythmicContrast: 0.7839286006055772
purpose: []
