name: zippoppow
favicon: null
layout_spectrum: 0.6777
typography_spectrum: 0.31292
title: 'zippoppow | official wordz'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#98cb00'
    - '#778c00'
    - '#a80000'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
