analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#98cb00'
    - '#778c00'
    - '#a80000'
  brandStrength: 1
  lightness: 0.6875
  rhythmicContrast: 0.25
  saturation: 0.75
cta: {}
layout_spectrum: 0.6777
name: zippoppow
opengraph: {}
purpose: []
typography_spectrum: 0.23261
